default_twitter: &default_twitter
  twitter_api_key: '20cH07N3zdjUvrzKBcMQaLBGJ'
  twitter_api_secret: 'DdzKmlKJ5Ga1BhVY15VV5xsJhz7zjWPvbFtiHnXDvTHtQBjL2L'

development:
  secret_key_base: e3da4c42490f9ddc6c3de44af05fd5c82c2671163eaccc4819c487fb12822b562913a61278a98a0c58ce5170659b766ebbc2f46e770044ff83c54bcf765e8521
  <<: *default_twitter

test:
  secret_key_base: df95151721dd48830548a6fe2e83fb7e7073e4cde19cb290b0119ba7c0e3edfdbabed8f8e17f647965ca1d1cf71793c1c84d172c7bd78ff82a14fe88a5a6a1b2
  <<: *default_twitter

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_API_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>
